/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TodoDto,
} from '../models/index';
import {
    TodoDtoFromJSON,
    TodoDtoToJSON,
} from '../models/index';

/**
 * 
 */
export class TodoApi extends runtime.BaseAPI {

    /**
     */
    async todoControllerGetTodosRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TodoDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/todo`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TodoDtoFromJSON));
    }

    /**
     */
    async todoControllerGetTodos(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TodoDto>> {
        const response = await this.todoControllerGetTodosRaw(initOverrides);
        return await response.value();
    }

}
