# ビルドステージ
FROM node:20.12.0 AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

# 実行ステージ
FROM node:20.12.0 AS runner

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --omit=dev --ignore-scripts

COPY --from=builder /app/dist ./dist

CMD ["npm", "run", "docker:prod"]
