/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoDto
 */
export interface TodoDto {
    /**
     * 
     * @type {number}
     * @memberof TodoDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TodoDto
     */
    task: string;
    /**
     * 
     * @type {boolean}
     * @memberof TodoDto
     */
    completed: boolean;
}

/**
 * Check if a given object implements the TodoDto interface.
 */
export function instanceOfTodoDto(value: object): value is TodoDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('task' in value) || value['task'] === undefined) return false;
    if (!('completed' in value) || value['completed'] === undefined) return false;
    return true;
}

export function TodoDtoFromJSON(json: any): TodoDto {
    return TodoDtoFromJSONTyped(json, false);
}

export function TodoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'task': json['task'],
        'completed': json['completed'],
    };
}

export function TodoDtoToJSON(json: any): TodoDto {
    return TodoDtoToJSONTyped(json, false);
}

export function TodoDtoToJSONTyped(value?: TodoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'task': value['task'],
        'completed': value['completed'],
    };
}

